### ISSUE TITLE
Seeking Clarification on Details of Electronic Devices

### ISSUE THREAD

**Issue by psycho-ygq** [Vandermode/SVN3#1]
Hello, I have read your paper and find your work very meaningful. I sincerely appreciate your contributions to this field. I would like to ask if you could kindly share more details about the lightweight electronic module (ISP) mentioned in your experiments. I would greatly appreciate any insights you could provide. Thank you!

**Comment by Vandermode** [comment]
Hi, thanks for your interest.

Are you asking details about the electronic hardware or just the electronic neural network we used in this work?

**Comment by psycho-ygq** [comment]
> 您好，感谢您的关注。
> 
> 您是在询问有关电子硬件的细节，还是只询问我们在这项工作中使用的电子神经网络的细节？

I want to learn more about the details of electronic hardware. From what I know, ISP can only handle simple image preprocessing tasks. How can ISP be used to implement complex models like CNN?

**Comment by Vandermode** [comment]
Yea, traditional ISP is fixed function without programmability. However, there are both System on chip (Soc) or software-defined ISP to support this functionality. For example, you can use FPGA platforms (Xilinx Zynq, Lattice CrossLink-NX) to design an ISP pipeline alongside a C-programmable processor, or SoCs like Raspberry Pi to blend ISP-like processing with C code.

**Comment by psycho-ygq** [comment]
> Yea, traditional ISP is fixed function without programmability. However, there are both System on chip (Soc) or software-defined ISP to support this functionality. For example, you can use FPGA platforms (Xilinx Zynq, Lattice CrossLink-NX) to design an ISP pipeline alongside a C-programmable processor, or SoCs like Raspberry Pi to blend ISP-like processing with C code.

I see. Thanks for your reply.

**Comment by psycho-ygq** [comment]
Sorry to bother you again, but I have one more question to ask. In Figure 6 of your supplementary materials, you mentioned the modeling of the optical front end. Your input is a point light source, and from the point light source to the metal metasurface array, you essentially intercepted the complex amplitude of the plane during the propagation of the spherical wave. Then, due to the modulation of the metasurface, a phase shift is added. However, I am curious as to why you used the ASM (Angular Spectrum Method) simulation from the metal metasurface plane to the sensor's receiving plane. One issue is that you are using incoherent light—can ASM be used in this case? Another issue is that you used a spherical wave earlier, but later you used ASM (which mainly simulates plane waves). Is this approach reasonable?

**Comment by Vandermode** [comment]
Hi, Given the questions you asked, I think you don't quite understand the ASM algorithm and the incoherent wave optics model. 
I don't think it's easy to explain it clearly here. 

In short, ASM itself only considers the coherent plane-to-plane wave propagation (it doesn't matter what kind of wavefront, e.g., plane or spherical or an arbitrary one, you are dealing with), for incoherent case, it serves as the building blocks to compute the system PSFs.

**Comment by psycho-ygq** [comment]
Thank you very much for your reply. I’m just starting to learn about optical computing, so I still have some confusion regarding incoherent wave optics. I will continue studying to deepen my understanding. I have an admittedly presumptuous request: would it be possible for you to share the code related to your modeling of this part? I would like to better understand the incoherent light propagation model described in your paper. I would be truly grateful.
